# Generated by Django 4.2.11 on 2024-05-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttoinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
