# Generated by Django 5.0.6 on 2024-07-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttoinventory',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipetoinventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
