# Generated by Django 5.0.6 on 2024-05-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
