# Generated by Django 4.2.11 on 2024-05-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_recipeinventory_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeinventory',
            old_name='total_quantity',
            new_name='total_amount',
        ),
    ]
